/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Interface.CompteInterface;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;

/**
 *
 * @author Dell
 */
public class Home extends javax.swing.JFrame {
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        destinataire.setVisible(false);
        labelDestinataire.setVisible(false);
        panelDC.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        contenuPrincipal = new javax.swing.JPanel();
        crediter = new javax.swing.JButton();
        Detail = new javax.swing.JButton();
        debiter = new javax.swing.JButton();
        transferer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        port = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numRef = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelDC = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dtDateCreation = new javax.swing.JLabel();
        dtSolde = new javax.swing.JLabel();
        dtCodeClient = new javax.swing.JLabel();
        dtNumRef = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dtTypeCompte = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panelTransation = new javax.swing.JPanel();
        destinataire = new javax.swing.JTextField();
        valider = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Montant = new javax.swing.JTextField();
        labelDestinataire = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        action = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        contenuPrincipal.setBackground(new java.awt.Color(51, 51, 51));
        contenuPrincipal.setToolTipText("");

        crediter.setText("Crediter");
        crediter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crediterActionPerformed(evt);
            }
        });

        Detail.setText("detailCompte");
        Detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailActionPerformed(evt);
            }
        });

        debiter.setText("Debiter");
        debiter.setBorder(null);
        debiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debiterActionPerformed(evt);
            }
        });

        transferer.setText("Transferer");
        transferer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfererActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numero du compte");

        port.setText("1099");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Port");

        numRef.setText("CT1");
        numRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numRefActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DES COMPTES BANCAIRES");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("APPLICATION CLIENT SERVEUR ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DE GESTION ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        ip.setText("127.0.0.1");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("IP");

        javax.swing.GroupLayout contenuPrincipalLayout = new javax.swing.GroupLayout(contenuPrincipal);
        contenuPrincipal.setLayout(contenuPrincipalLayout);
        contenuPrincipalLayout.setHorizontalGroup(
            contenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenuPrincipalLayout.createSequentialGroup()
                .addGroup(contenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenuPrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(contenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenuPrincipalLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2))
                            .addComponent(jLabel11)
                            .addGroup(contenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ip, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(transferer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(crediter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(debiter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Detail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenuPrincipalLayout.createSequentialGroup()
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel3))
                                .addComponent(port, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(numRef, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                    .addGroup(contenuPrincipalLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel12)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contenuPrincipalLayout.createSequentialGroup()
                .addGroup(contenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenuPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(contenuPrincipalLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel4)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        contenuPrincipalLayout.setVerticalGroup(
            contenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenuPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(debiter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(crediter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(transferer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Detail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jLabel5.setText("NUMERO DE REFERENCE");

        jLabel6.setText("NUMERO DU PROPRIETAIRE");

        jLabel7.setText("SOLDE");

        jLabel8.setText("DATE DE CRATION");

        dtDateCreation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dtDateCreation.setText("jLabel5");

        dtSolde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dtSolde.setText("jLabel5");

        dtCodeClient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dtCodeClient.setText("jLabel5");

        dtNumRef.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dtNumRef.setText("jLabel5");

        jLabel9.setText("TYPE DE COMPTE");

        dtTypeCompte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dtTypeCompte.setText("jLabel5");

        jLabel13.setText("CDF");

        javax.swing.GroupLayout panelDCLayout = new javax.swing.GroupLayout(panelDC);
        panelDC.setLayout(panelDCLayout);
        panelDCLayout.setHorizontalGroup(
            panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDCLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(70, 70, 70)
                .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtTypeCompte)
                    .addComponent(dtDateCreation)
                    .addGroup(panelDCLayout.createSequentialGroup()
                        .addComponent(dtSolde)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addComponent(dtCodeClient)
                    .addComponent(dtNumRef))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panelDCLayout.setVerticalGroup(
            panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDCLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDCLayout.createSequentialGroup()
                        .addComponent(dtNumRef)
                        .addGap(18, 18, 18)
                        .addComponent(dtCodeClient)
                        .addGap(18, 18, 18)
                        .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dtSolde)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addComponent(dtDateCreation))
                    .addGroup(panelDCLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(panelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(dtTypeCompte))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        destinataire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinataireActionPerformed(evt);
            }
        });

        valider.setText("Valider");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        jLabel1.setText("Montant");

        labelDestinataire.setText("Numero destinataire");

        message.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout panelTransationLayout = new javax.swing.GroupLayout(panelTransation);
        panelTransation.setLayout(panelTransationLayout);
        panelTransationLayout.setHorizontalGroup(
            panelTransationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransationLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(panelTransationLayout.createSequentialGroup()
                        .addGroup(panelTransationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Montant, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDestinataire)
                            .addComponent(destinataire, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelTransationLayout.setVerticalGroup(
            panelTransationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransationLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Montant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDestinataire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destinataire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(valider)
                .addGap(26, 26, 26)
                .addComponent(message)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        action.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        action.setText("DEBITER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(action)
                            .addComponent(panelTransation, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(action)
                .addGap(18, 18, 18)
                .addComponent(panelTransation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(contenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numRefActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        operation();
    }//GEN-LAST:event_validerActionPerformed

    private void destinataireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinataireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinataireActionPerformed

    private void crediterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crediterActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        this.action.setText("CREDITER");
         this.panelTransation.setVisible(true);
        this.panelDC.setVisible(false);
        destinataire.setVisible(false);
        labelDestinataire.setVisible(false);
        this.message.setText("");
        this.Montant.setText("");
    }//GEN-LAST:event_crediterActionPerformed

    private void debiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debiterActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        this.action.setText("DEBITER");
        this.panelTransation.setVisible(true);
        this.Montant.setText("");
        this.panelDC.setVisible(false);
        destinataire.setVisible(false);
        labelDestinataire.setVisible(false);
        this.message.setText("");
    }//GEN-LAST:event_debiterActionPerformed

    private void transfererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfererActionPerformed
// TODO add your handling code here:
        this.action.setText("TRANSFERER");
        this.panelTransation.setVisible(true);
        this.panelDC.setVisible(false);
        destinataire.setVisible(true);
        this.message.setText("");
        labelDestinataire.setVisible(true); 
        this.Montant.setText("");// TODO add your handling code here:
        this.destinataire.setText("");
    }//GEN-LAST:event_transfererActionPerformed

    private void DetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        this.action.setText("DETAILS DU COMPTE");
        this.message.setText("");
        operation();
    }//GEN-LAST:event_DetailActionPerformed

    private void detailsClientActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        this.action.setText("DETAILS DU CLIENTS");
        this.panelTransation.setVisible(false);
        this.panelDC.setVisible(false); 
        this.message.setText("");

    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    private void operation()
    {
        String url = null;
      try { 
         // Getting the registry 
        url = "rmi://"+this.ip.getText()+":"+ this.port.getText()+"/OperationBanque";
        System.out.println("The url is "+url);
        CompteInterface OperationBanque = (CompteInterface) Naming.lookup (url);         

        switch(this.action.getText()){
                case "DEBITER" :  
                    OperationBanque.debiter(this.numRef.getText(), Double.parseDouble( this.Montant.getText()));
                    this.message.setText("L'operation s'est effectuee avec succes");
                    break;
                    
                case "CREDITER" :  
                    OperationBanque.crediter(this.numRef.getText(), Double.parseDouble( this.Montant.getText()));
                    this.message.setText("L'operation s'est effectuee avec succes");
                    break;
                    
                case "TRANSFERER" :  
                    OperationBanque.transferer(this.numRef.getText(), this.destinataire.getText(),  Double.parseDouble( this.Montant.getText()));
                    this.message.setText("L'operation s'est effectuee avec succes");
                    break;
                    
                case "DETAILS DU COMPTE" :  
                    String parameters[];
                    parameters = OperationBanque.detailsCompte(this.numRef.getText()).split(" ");
                    //this.numRef+" "+ this.codeClient +" "+type+" "+this.datecreation+" "+this.solde;
                    this.dtNumRef.setText(parameters[0]);
                    this.dtCodeClient.setText(parameters[1]);
                    this.dtTypeCompte.setText(parameters[2]);
                    this.dtDateCreation.setText(parameters[3]);
                    this.dtSolde.setText(parameters[4]);
                    this.panelTransation.setVisible(false);
                    this.panelDC.setVisible(true);
                    break;
                }
      } catch (MalformedURLException | NotBoundException | RemoteException e) { 
         System.err.println("Client exception: " + e.toString()); 
         this.message.setText("ERROR : the custumer cannot find the server on ["+url+"] , Please, Verify the server address and try again !");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Detail;
    private javax.swing.JTextField Montant;
    private javax.swing.JLabel action;
    private javax.swing.JPanel contenuPrincipal;
    private javax.swing.JButton crediter;
    private javax.swing.JButton debiter;
    private javax.swing.JTextField destinataire;
    private javax.swing.JLabel dtCodeClient;
    private javax.swing.JLabel dtDateCreation;
    private javax.swing.JLabel dtNumRef;
    private javax.swing.JLabel dtSolde;
    private javax.swing.JLabel dtTypeCompte;
    private javax.swing.JTextField ip;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelDestinataire;
    private javax.swing.JLabel message;
    private javax.swing.JTextField numRef;
    private javax.swing.JPanel panelDC;
    private javax.swing.JPanel panelTransation;
    private javax.swing.JTextField port;
    private javax.swing.JButton transferer;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
